// <auto-generated />
using System;
using EindCasus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EindCasus.Migrations
{
    [DbContext(typeof(CursusDbContext))]
    [Migration("20210321163216_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursistCursusInstantie", b =>
                {
                    b.Property<int>("CursistenId")
                        .HasColumnType("int");

                    b.Property<int>("CursusInstantiesId")
                        .HasColumnType("int");

                    b.HasKey("CursistenId", "CursusInstantiesId");

                    b.HasIndex("CursusInstantiesId");

                    b.ToTable("CursistCursusInstantie");
                });

            modelBuilder.Entity("EindCasus.Models.Cursist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AchterNaam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Naam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cursist");
                });

            modelBuilder.Entity("EindCasus.Models.Cursus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Cursus");
                });

            modelBuilder.Entity("EindCasus.Models.CursusInstantie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CursusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CursusId");

                    b.ToTable("CursusInstantie");
                });

            modelBuilder.Entity("EindCasus.Models.BedrijfsMedewerker", b =>
                {
                    b.HasBaseType("EindCasus.Models.Cursist");

                    b.Property<string>("Afdeling")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BedrijfsNaam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfferteNummer")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("BedrijfsMedewerker");
                });

            modelBuilder.Entity("EindCasus.Models.Particulier", b =>
                {
                    b.HasBaseType("EindCasus.Models.Cursist");

                    b.Property<int>("HuisNummer")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("RekeningNummer")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("StraatNaam")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WoonPlaats")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Particulier");
                });

            modelBuilder.Entity("CursistCursusInstantie", b =>
                {
                    b.HasOne("EindCasus.Models.Cursist", null)
                        .WithMany()
                        .HasForeignKey("CursistenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EindCasus.Models.CursusInstantie", null)
                        .WithMany()
                        .HasForeignKey("CursusInstantiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EindCasus.Models.CursusInstantie", b =>
                {
                    b.HasOne("EindCasus.Models.Cursus", null)
                        .WithMany("CursusInstanties")
                        .HasForeignKey("CursusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EindCasus.Models.BedrijfsMedewerker", b =>
                {
                    b.HasOne("EindCasus.Models.Cursist", null)
                        .WithOne()
                        .HasForeignKey("EindCasus.Models.BedrijfsMedewerker", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EindCasus.Models.Particulier", b =>
                {
                    b.HasOne("EindCasus.Models.Cursist", null)
                        .WithOne()
                        .HasForeignKey("EindCasus.Models.Particulier", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EindCasus.Models.Cursus", b =>
                {
                    b.Navigation("CursusInstanties");
                });
#pragma warning restore 612, 618
        }
    }
}
